base_url = "https://syedzayyan.com/molrus/"
title = "Molrus"
description = "A cheminformatics library written in Rust, made with love."

compile_sass = true
build_search_index = true

[search]
index_format = "elasticlunr_json"

[markdown]
highlight_code = true
highlight_theme = "kronuz"
#highlight_theme = "css"
#highlight_themes_css = [
#  { theme = "base16-ocean-dark", filename = "syntax-theme-dark.css" },
#  { theme = "base16-ocean-light", filename = "syntax-theme-light.css" },
#]

[link_checker]
internal_level = "warn"

[extra]
author = "SZM"
